import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@components/Navbar";
import "./globals.css";
import Footer from "@components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bizgrow Digital",
  description: "Generated by create next app",
  icons: {
    icon: "/site-logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans bg-white text-black">
        <Navbar />
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
