import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@components/Navbar";
import "./globals.css";
import Footer from "@components/Footer";
import { Providers } from "./providers";
import SmoothScroll from "@components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bizgrow Digital",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
   
  },
};

// app/layout.tsx
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}suppressHydrationWarning={true}>
      {/* overflow-x-hidden yahan se hata dein */}
      <body className="font-sans bg-white text-black antialiased overflow-x-clip">
        <Providers>
          <Navbar />
          <SmoothScroll>
            <main>{children}</main>
            <Footer/>
          </SmoothScroll>
        </Providers>
      </body>
    </html>
  );
}
