import { Playfair_Display, Montserrat } from "next/font/google"; // Naye fonts import kiye
import Navbar from "@components/Navbar";
import "./globals.css";
import Footer from "@components/Footer";
import { Providers } from "./providers";
import SmoothScroll from "@components/SmoothScroll";
import ChatBot from "@components/ChatBot";
import { Analytics } from '@vercel/analytics/next';

// Headings ke liye Premium Font
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["700", "900"],
  style: ['italic', 'normal'], // Italic bht unique lagta hai is style mein
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "400", "500"],
});


export const metadata = {
  title: "Bizgrow Digital",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
   
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${montserrat.variable}`} suppressHydrationWarning={true}>
      <body className="font-body bg-[#FDFCF9] text-[#1f2937] antialiased overflow-x-clip">
        <Providers>
          <Navbar />
          <SmoothScroll>
            <main>{children}
               <Analytics />
            </main>
            <Footer/>
          </SmoothScroll>
          <ChatBot />
        </Providers>
      </body>
    </html>
  );
}